CREATE TABLE Employee (
    SSN INT IDENTITY(1,1) PRIMARY KEY,
    Fname NVARCHAR(255) NOT NULL,
    Lname NVARCHAR(255) NOT NULL,
    Gender CHAR NOT NULL CHECK (Gender IN ('M','F')),
    BirthDate DATE NOT NULL,
    MSSN INT NOT NULL,
    DNum INT NOT NULL,
    FOREIGN KEY (MSSN) REFERENCES Employee(SSN)
    --FOREIGN KEY (DNum) REFERENCES Department(DNum)
);

CREATE TABLE Department (
    DNum INT IDENTITY(1,1) PRIMARY KEY,
    DName NVARCHAR(255) NOT NULL,
    Location NVARCHAR(300) NOT NULL
);

CREATE TABLE Project (
    PNumber INT PRIMARY KEY,
    PName NVARCHAR(255) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    DNum INT NOT NULL,
    FOREIGN KEY (DNum) REFERENCES Department(DNum)
);

CREATE TABLE Dependent (
    DName NVARCHAR(255) PRIMARY KEY,
    Gender CHAR NOT NULL CHECK (Gender IN ('M','F')),
    BirthDate DATE NOT NULL,
    ESSN INT NOT NULL,
    FOREIGN KEY (ESSN) REFERENCES Employee(SSN) ON DELETE CASCADE
);

CREATE TABLE Work_Hours (
    ESSN INT NOT NULL,
    PNumber INT NOT NULL,
    Working_hours INT DEFAULT 0 NOT NULL,
    FOREIGN KEY (ESSN) REFERENCES Employee(SSN) ON DELETE CASCADE,
    FOREIGN KEY (PNumber) REFERENCES Project(PNumber) ON DELETE CASCADE,
    primary key (ESSN, PNumber)
);

CREATE TABLE Management (
    ESSN INT NOT NULL,
    DNum INT NOT NULL,
    Hire_date DATE NOT NULL,
    FOREIGN KEY (ESSN) REFERENCES Employee(SSN) ON DELETE CASCADE,
    FOREIGN KEY (DNum) REFERENCES Department(DNum) ON DELETE CASCADE,
    PRIMARY KEY (ESSN, DNum)
);

ALTER TABLE Employee
ADD  FOREIGN KEY (DNum) REFERENCES Department(DNum);